### ISSUE TITLE
Source-Code?

### ISSUE THREAD

**Issue by pvizeli** [codenotary/cas#206]
Where is the source code to build it from the source?

**Comment by ufierro** [comment]
hey @pvizeli , vcn Is going to through some refactoring and an open source version of the source code will be available soon

**Comment by leogr** [comment]
I can understand a massive refactor, but getting rid of the previous source code is a bad idea. Honestly, it's not fair for previous contributors. Furthermore, it does not allow us to look at the project's history (that can be useful to reference old behaviors).
Moreover, the previous code is still available in closed PRs, which can lead users to confusion.

Anyways, just my 2 cents :)
