### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by pvizeli** [codenotary/cas#248]
**What happened**

I have just with a couple of parallels builds a lot of timeouts. I'm a bit scared about what will happen if we roll that out to 200k-300k users. That not all CI starting to fail, I was forced to add retry logic and sleeps.

```
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.207.232.93:443: i/o timeout"
```

**What you expected to happen**

No timeouts

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
```shell
# run "cas info" and copy/paste the output here
```

**Additional info (any other context about the problem)**

**Comment by ufierro** [comment]
Hi @pvizeli; are all requests coming from the same IP Adress? And if so, are there many other requests coming from that address while your CI runs?

**Comment by pvizeli** [comment]
We using Github CI with 60 workers. I don't know if they share the IP address. I was also thinking that it's maybe a Firewall protection rule which is too sensitive.

**Comment by ufierro** [comment]
> We using Github CI with 60 workers. I don't know if they share the IP address. I was also thinking that it's maybe a Firewall protection rule which is too sensitive.
 
Are they self managed or Github hosted runners? I'm inclined to believe this might have something to do with our rate limiting mechanism, in which case an exception would need to be added to allow the high traffic volume; assuming they do share an IP address

**Comment by vchaindz** [comment]
we're going to look into the traffic pattern. It absolutely sounds like the communication is hitting the ceiling of our configured limits. But that is something we can fix quickly after analyzing the traffic.
We'll keep you posted.

**Comment by pvizeli** [comment]
Thanks. The workers are Github-hosted runners, sponsored by Microsoft. Currently I would say, it look like if a worker is blocked and if it is reused for a new job, they fails too

**Comment by SimoneLazzaris** [comment]
I have checked the configuration of our DoS limiting filter, and increased a couple of thresholds. Can you please check again if the problem is still there?

**Comment by pvizeli** [comment]
Yes: https://github.com/home-assistant/docker-base/actions/runs/1491458525
I try this release now multiple times since yesterday and it was never successful because in the last step (on the python builds) it get a timeout and all fails. So hopefully it finish now successfully :) Thanks for the support.

**Comment by SimoneLazzaris** [comment]
It seems that this build succeeded, so it is (was) our limiter that gets in the way. I removed any limits at around 09:21 UTC, but from the logs it seems that the CAS operation were already completed.
I'd like to have another test with a slightly different configuration (a longer time frame for threshold computation); from our metrics it should work, let me know if/when we can make this test.

**Comment by pvizeli** [comment]
Looks good now :) Thanks for all ❤️
