### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by frenck** [codenotary/cas#263]
**What happened**

Timeouts are appearing, both in CI (GitHub Actions) and local.

My local connection/machine (Europe, The Netherlands)

![image](https://user-images.githubusercontent.com/195327/157487360-d508fa85-f540-4589-9d07-132ed06d54b4.png)

GitHub Actions seems to experience the same:

![image](https://user-images.githubusercontent.com/195327/157487448-12f13c8f-54fd-4ad3-98e2-737d5db9b7df.png)

(issue occurring on all runs, in different repositories/workflows).

**What you expected to happen**

Well, not to timeout :)

**How to reproduce it (as minimally and precisely as possible)**

See above

**Environment**
```shell
# run "cas info" and copy/paste the output here
```

Interesting.... `cas info` is not a valid command. Please advise.

**Additional info (any other context about the problem)**

**Comment by frenck** [comment]
Possibly related reports here as well: <https://github.com/home-assistant/supervisor/issues/3495>

**Comment by frenck** [comment]
As per Discord feedback, this was related to a heavy load on the API, which has been resolved.

Closing the issue for that reason.

**Comment by nodomain** [comment]
Can not confirm. Seems I should continue tomorrow?
![image](https://user-images.githubusercontent.com/104389/157539067-b71a4370-0930-4d8f-9b04-6b01fcd19f91.jpeg)

**Comment by quizzical86** [comment]
I also have the Timeout while processing CodeNotary error

**Comment by frenck** [comment]
Re-opening the issue, as it is still happening at this point as it seems.

**Comment by sdp74** [comment]
From Belgium 
Pinging cas.codenotary.com [35.168.17.115] with 32 bytes of data:
Request timed out.

**Comment by vchaindz** [comment]
icmp is blocked, but the service is back up.

**Comment by frenck** [comment]
All good now 👍
