### ISSUE TITLE
Signature doesn't match provided public key

### ISSUE THREAD

**Issue by pvizeli** [codenotary/cas#273]
> Error: operation aborted : rpc error: code = Canceled desc = signature doesn't match provided public key
> previously trusted Community Attestation Service changed its signature. In order to trust again the server please provide a new public > key or remove .cas-trusted-signing-pub-key stored in home folder.

Anything change? does the client self recover from that?

**Comment by tomekkolo** [comment]
Hi @pvizeli, we were upgrading CAS instance and that could cause the issue. All should be back to normal. Can you check ?

**Comment by pvizeli** [comment]
@tomekkolo I tested it shortly and it seems to work again with the public key from the website. Thanks
