### ISSUE TITLE
Parallel notarization issues

### ISSUE THREAD

**Issue by javihernandez** [codenotary/cas#275]
Hi,

I'd like to report this issue as it's unclear to me what's happening when I try to notarize several artifacts at the same time. Or even if it's not supported or a recommended way of interacting with CAS.

**What happened**
We use CAS to notarize all the artifacts that we produce from the [AlmaLinux Build System](https://github.com/AlmaLinux/build-system). To easily achieve this, we created [cas_wrapper](https://git.almalinux.org/almalinux/cas_wrapper), which is just a Python module that simplifies the interaction with the cas binary. Currently, we're having problems when trying to notarize several artifacts at the same time, which can be possible thanks to [this method](https://git.almalinux.org/almalinux/cas_wrapper/src/commit/98ca413db7e7eda2e064507d1be340a0b256c938/cas_wrapper.py#L156-L184) in _cas_wrapper_.

The problem is that sometimes we fail to notarize artifacts because the cas binary returns: ```While parsing config: unexpected end of JSON input```

**What you expected to happen**
I expect that everything gets notarized without any problem

**How to reproduce it (as minimally and precisely as possible)**
Although we're mostly experiencing this issue in our s390x build nodes, I could reproduce it locally (x86_64).
I've prepared this [parallel-notarization-experiment.tar.gz](https://github.com/codenotary/cas/files/9371475/parallel-notarization-experiment.tar.gz) so you can reproduce it locally very easily. You have to:
1. Unpack the experiment: ```tar xvzf parallel-notarization-experiment.tar.gz```
2. Go into the folder: ```cd parallel-notarization-experiment```
3. Run the experiment: ```CAS_API_KEY=<insert-your-cas-api-key> ./test-case.sh 6```

It's intermittent, and the chances of failure increase as you increase the number of parallel calls to _cas_.

As I mentioned earlier, I can reproduce the problem in both x86_64 and in s390x platforms, using the corresponding cas binaries taken from [here](https://github.com/codenotary/cas/releases/tag/v1.0.2).

**Environment**
```shell
[alt@1a2c118ad9dd build-node]$ cas info
Error: unknown command "info" for "cas"
Run 'cas --help' for usage.
```
:trollface: Please update the template :smile: 

If you're looking for the versions I'm using, I can reproduce the problem in both v1.0.0 and v1.0.2.
Let me know if you want me to provide anything else.

**Additional info (any other context about the problem)**
I googled around ```While parsing config: unexpected end of JSON input``` and found [this](https://stackoverflow.com/questions/27994327/golang-json-unmarshal-unexpected-end-of-json-input). I'm not familiar with Golang but I think it might be related to the issue I'm having here.

**Comment by tomekkolo** [comment]
Hey @javihernandez , please find a fix for this issue https://github.com/codenotary/cas/pull/276 . I've tested with your script and no errors. 

as to cas info, there is no such command in cas. Use cas --version.

**Comment by javihernandez** [comment]
Hey @tomekkolo, thanks for you super fast reply and fix.

> Hey @javihernandez , please find a fix for this issue #276 . I've tested with your script and no errors.

I tested it too using our cas_wrapper and worked like a charm, thanks!!
Do you have an idea of when this change will reach master and/or have a new CAS release?
No rush on our side, for now, we have implemented a stop gap solution until we get a proper new release, but I'm asking just to have an idea 

> as to cas info, there is no such command in cas. Use cas --version.

Yeah, that's why I was asking you to update the template, but it's okay, I created this 'thank you' [PR](https://github.com/codenotary/cas/pull/282)

**Comment by tomekkolo** [comment]
Ah yes, you were referring to issue template :) Thanks for PR :) 

We will release next week.

**Comment by javihernandez** [comment]
> Ah yes, you were referring to issue template :) Thanks for PR :)

No worries, is the best I can do after your quick reaction to my issue. Thanks!

> We will release next week.

Ok, I'll stay tuned. Thanks again! 

From my side, this issue can be closed as my problem is already solved, but I'll leave it open, just in case you want to close it after the new release is in place
