### ISSUE TITLE
Register account

### ISSUE THREAD

**Issue by bropat** [codenotary/cas#296]
Hi,

I have read the quick start guide and don't understand how to register for a free account at point 1. When I follow the link (https://cas.codenotary.com/), I can't find an option to register.
Can anyone help me?

Thanks!

Regards
Patrick

**Comment by emkaminsk** [comment]
Hi Patrick

Thank you for your interest in CAS. We regret to inform that we have suspended registration of new accounts for the CAS service. There was not much interest in the service and we made a decision to suspend new registrations. For existing accounts the service is still running.

We apologize for any inconvenience this may cause and appreciate your understanding.

Best regards
Marcin

**Comment by bropat** [comment]
Hi Marcin

Thank you very much for the quick feedback. That is very pity. I needed it for Home Assistant :)
