### ISSUE TITLE
Codenotary Community Attestation Service down?

### ISSUE THREAD

**Issue by frenck** [codenotary/cas#301]
**What happened**

![image](https://user-images.githubusercontent.com/195327/228664589-650d1e17-e93b-4dca-8578-9b11ba717158.png)

@ Home Assistant project:

![CleanShot 2023-03-29 at 22 52 50](https://user-images.githubusercontent.com/195327/228664651-ea2cf24c-1e5f-4443-84e7-6f606e9a1590.png)

**What you expected to happen**

To work :)

**How to reproduce it (as minimally and precisely as possible)**

See above, try to authenticate.

**Additional info (any other context about the problem)**

**Comment by SimoneLazzaris** [comment]
Hi @frenck 
unfortunately we had an hardware issue that affected the service.
It was solved today at 04:51 UTC

It should be working now, can you confirm?

**Comment by frenck** [comment]
Yes, we are back online. Thanks 👍
