### ISSUE TITLE
https://cas.codenotary.com/ down

### ISSUE THREAD

**Issue by alexbelgium** [codenotary/cas#315]
**What happened**
https://cas.codenotary.com/ is down
https://cas-validator.home-assistant.io indicates validation not successful

**What you expected to happen**
Successful notarization 

**How to reproduce it (as minimally and precisely as possible)**
Try notarize container, or go to website

**Environment**
```shell
# run "cas --version" and copy/paste the output here
```

**Additional info (any other context about the problem)**

**Comment by vchaindz** [comment]
CAS has been retired as immudb Vault is up and running for a while now. Please check https://vault.immudb.io - it's a free service as well for many if not most use cases.
