### ISSUE TITLE
CAS Login Error

### ISSUE THREAD

**Issue by paddyxi** [codenotary/cas#316]
**CAS Login Error**

<img width="1032" alt="image" src="https://github.com/codenotary/cas/assets/43661012/381cb77d-77b6-4c29-a150-21e516db86e3">

**Please FYI picture **

**Environment**
```shell```
<img width="403" alt="image" src="https://github.com/codenotary/cas/assets/43661012/9151b22f-13aa-487b-a446-668b5ea3b64b">

**Comment by vchaindz** [comment]
https://github.com/codenotary/cas/issues/315

**Comment by vchaindz** [comment]
https://github.com/codenotary/cas/issues/315
